version: '3.8'

services:
  villma-website:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: villma-website
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:      
      - FIREBASE_API_KEY=${FIREBASE_API_KEY}
      - FIREBASE_AUTH_DOMAIN=${FIREBASE_AUTH_DOMAIN}
      - FIREBASE_PROJECT_ID=${FIREBASE_PROJECT_ID}
      - FIREBASE_STORAGE_BUCKET=${FIREBASE_STORAGE_BUCKET}
      - FIREBASE_MESSAGING_SENDER_ID=${FIREBASE_MESSAGING_SENDER_ID}
      - FIREBASE_APP_ID=${FIREBASE_APP_ID}
      - FIREBASE_MEASUREMENT_ID=${FIREBASE_MEASUREMENT_ID}
      
      - WEBSITE_CONTACT_GMAIL_USER=${WEBSITE_CONTACT_GMAIL_USER}
      - WEBSITE_CONTACT_GMAIL_APP_PASSWORD=${WEBSITE_CONTACT_GMAIL_APP_PASSWORD}
      
      - SITE_URL=${SITE_URL}
      - APP_NAME=${APP_NAME}
