name: Deploy

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: build-artifact

      - name: Deploy to server
        run: |
          echo "Deploying..."
          # e.g. rsync, scp, kubectl apply, etc.
